#!/bin/bash
# jkb 19/2/2025

function setup
{
    local c=$1
    local v=$2
    
    if [ $c -ge $N ] ; then
        let "v -= $N"
        let "c -= $N"
        echo "expand $c $v  (N = $N)"
        expand $c $v
    fi
}

function expand
{
    local c=$1
    local v=$2
    while [ $v -lt $N ] ; do
        let "v+=$v"
        r=$(($RANDOM % 2 ))
        echo $r
        c=$((2*$c + $r))
        echo "v = $v, c = $c"
    done
    if [ $c -lt $N ] ; then
        return $c
    else
        setup $c $v
    fi
}

declare -i N=$1
echo "coroutine $N"

declare -i c=$N
declare -i v=$(($N + 1))

echo setup $c $v
setup $c $v

echo $?
