#!/bin/bash
# jkb 19/2/2025

declare -i N=$1

declare -i c=$N
declare -i v=$(($N + 1))

echo "nested $N"

echo  "v = $v, c = $c"

while [ $c -ge $N ] ; do
    v=$(($v - $N))
    c=$(($c - $N))
    echo "inner v = $v, c = $c"
    while [ $v -lt $N ] ; do
        v=$((2*$v))
        r=$(($RANDOM % 2 ))
        echo $r
        c=$((2*$c + $r))
        echo "v = $v, c = $c"
    done
done

echo $c
